export const SOCKET = {
  Events: {
    Channel_Updates: 'channel-updates',
  },
  Type: {
    Removal: 'removal',
  },
  Listeners: {
    Bulk_Status_Update: 'bulk-user-status-update',
    User_Status_Update: 'user-status-update',
    Receive_Message: 'receive-message',
    Channel_Added: 'channel-added',
    Channel_Deleted: 'channel-deleted',
    New_Channel: 'new-channel',
    Members_Added: 'members-added',
    Message_Status_Updated: 'message-status-updated',
    Messages_Read: 'messages-read',
    Message_Deleted: 'message-deleted',
    Message_Pin: 'message-pin',
    Message_Unpin: 'message-unpin',
    Message_Updated: 'message-updated',
    Message_Reaction_Updated: 'message-reaction-updated',
    Account_Deactivated: 'account-deactivated',
    Admin_Deactivation: 'admin-deactivation',
    Admin_Deletion: 'admin-deletion',
    Team_Deletion: 'team-deleted',
    Admin_Settings_Updated: 'admin-settings-updated',
    Chat_Pin_Updated: 'chat-pin-updated',
    Chat_Muted:'chat-muted',  
    Chat_Unmuted:'chat-unmuted',
    Password_Updated: 'password-updated',
    Logout_From_All_Devices: 'logout-from-all-devices',
    Message_Favorite: 'message-favorite',
    Member_Removed_From_Channel: 'member-removed-from-channel',
    Member_Added_To_Channel: 'member-added-to-channel',
    Member_Role_Updated: 'member-role-updated',
    Member_Left_Channel: 'member-left-channel',
    Channel_Left: 'channel-left',
    // dnd
    Do_Not_Disturb_Updated: 'dnd_status_updated',
    // member status/role
    Member_Status_Updated: 'member_status_updated',
    // call
    Call_Ended: 'call-ended',
  },
  Emitters: {
    Message_Delivered: 'message-delivered',
    Message_Seen: 'message-seen',
    Typing: 'typing',
    Join_Room: 'join-room',
    Send_Message: 'send-message',
    Channel_Created: 'channel-created',
    Set_Online: 'set-online',
    Set_Away: 'set-away',
    Add_Reaction: 'add-reaction',
    Remove_Reaction: 'remove-reaction',
    Member_Role_Updated: 'member-role-updated',
    Member_Left_Channel: 'member-left-channel',
    Member_Removed_From_Channel: 'member-removed-from-channel',
    Request_Status_Update: 'request-status-update',

    // call
    Rejoin_Call: 'rejoin-call',
    Initiate_Call: 'initiate-call',
    Accept_Call: 'accept-call',
    Decline_Call: 'decline-call',
    End_Call: 'end-call',
    Toggle_Video: 'toggle-video',
    Toggle_Audio: 'toggle-audio',
    Ice_Candidate: 'ice-candidate',
    Webrtc_Offer: 'webrtc-offer',
    Webrtc_Answer: 'webrtc-answer',
    Sync_Participant_State: 'sync-participant-state',
    // e2e encryption
    Exchange_Encryption_Key: 'exchange-encryption-key',
    Encryption_Key_Received: 'encryption-key-received',

    // remote control
    Request_Remote_Control: 'request-remote-control',
    Accept_Remote_Control: 'accept-remote-control',
    Deny_Remote_Control: 'deny-remote-control',
    Stop_Remote_Control: 'stop-remote-control',

    // virtual office
    VO_Join_Room: 'vo:join-room',
    VO_Leave_Room: 'vo:leave-room',
    VO_Get_Rooms: 'vo:get-rooms',
    VO_Send_Quick_Message: 'vo:send-quick-message',
  },
  VOListeners: {
    Room_Update: 'vo:room-update',
    Rooms_State: 'vo:rooms-state',
    User_Joined_Room: 'vo:user-joined-room',
    User_Left_Room: 'vo:user-left-room',
    Quick_Message_Received: 'vo:quick-message-received',
  },
}
