export const BASE_URL = import.meta.env.VITE_API_BASE_URL

const URL = {
  Auth: {
    CheckEmail: 'auth/check-email',
    Login: 'auth/login',
    ForgotPassword: 'auth/forgot-password',
    VerifyOtp: 'auth/verify-otp',
    ResendOtp: 'auth/resend-otp',
    ResetPassword: 'auth/reset-password',
  },

  Profile: {
    UpdateDetails: 'account/updateProfile',
    Details: 'account/getUserDetails',
    UpdatePassword: 'account/updatePassword',
    Logout: 'account/logout',
    LogoutAllDevices: 'account/logout-all-devices',
  },
  Settings: {
    GetSettings: 'setting',
    GetPublicSettings: 'setting/public',
  },
  Team: {
    Dashboard: 'team/dashboard',
    CreateTeam: 'team/create',
    AddTeam: 'team/add',
    SetupProfile: 'team/setup/profile',
    TeamList: 'team',
    CurrentTeam: 'team/current-team',
    FindTeam: 'team/find',
    JoinTeam: 'team/join',
    DoNotDisturb: 'team/update/do-not-disturb',
    InviteTeamMembers: 'team/invite/member',
    CreateChannel: 'channel/create',
    GetAllTeams: 'team/all',
    GetAllTeamsMemberList: 'team/members',
    GetAllTeamSetting: 'team-setting',
    TeamUpdateStatus: 'team/update/role-status',
    GetAllCustomFieldList: 'custom-field/all',
    CreateCustomField: 'custom-field/create',
    DeleteCustomField: 'custom-field/delete',
    DeleteTeamMember: 'team/users',
    UpdateCustomField: 'custom-field/update',
    UpdateTeamSetting: 'team-setting/update',
    UserCustomFields: 'custom-field/user/value',
    LeaveTeam: 'team/leave',
    UpdateTeam: 'team/update/profile',
  },
  Chat: {
    GetConversations: 'message/conversations',
    GetMessages: 'message',
    GetMessageById: 'message/get/:id',
    SearchMessages: 'message/search',
    SendMessage: 'message/start',
    MessageReaction: 'message/reaction',
    DeleteMessage: 'message/delete',
    PinMessage: 'message/pin',
    UnpinMessage: 'message/unpin',
    FavoriteMessage: 'message/favorite',
    UnfavoriteMessage: 'message/unfavorite',
    EditMessage: 'message/update',
    PinConversation: 'message/conversation/pin',
    GetTeamChannels: 'channel/team',
    GetAllFiles: 'message/files',
    MuteChat: 'message/mute',
    UnmuteChat: 'message/unmute',
    GetMutedChats: 'message/muted-chats',
  },
  Reminders: {
    SetReminder: 'reminder/set',
    CancelReminder: 'reminder/cancel',
    DeleteReminder: 'reminder/deletee',
    GetReminder: 'reminder',
  },
  Channel: {
    GetChannel: 'channel/info/:id',
    GetChannelMembers: 'channel/members',
    LeaveChannel: 'channel/leave',
    RemoveChannelMember: 'channel/members/remove',
    UpdateChannelMemberRole: 'channel/members/update/role',
    UpdateChannel: 'channel/:id',
    DeleteChannel: 'channel/delete',
    AddMemberToChannel: 'channel/members/add',
    ChannelUpdateStatus: 'channel/update/role-status',
  },
  FAQ: {
    GetAllFaqs: 'faq',
    CreateFaq: 'faq/create',
    UpdateFaq: 'faq/update/:id',
    UpdateFaqStatus: 'faq/status/:id',
    DeleteFaq: 'faq/delete',
  },
  Page: {
    GetAllPages: 'page',
    CreatePage: 'page/create',
    UpdatePage: 'page/update/:id',
    UpdatePageStatus: 'page/status/:id',
    DeletePage: 'page/delete',
  },
  Wallet: {
    GetWallet: 'wallet',
    GetWalletBalance: 'wallet/balance',
    GetWalletTransactions: 'wallet/transactions',
    InitiatePayment: 'payment/initiate',
    VerifyPayment: 'payment/verify',
  },
  Plan: {
    GetPlans: 'plan',
    GetPlanBySlug: 'plan/slug/:slug',
    GetPlanById: 'plan/:id',
  },
  Subscription: {
    Calculate: 'subscription/calculate',
    Subscribe: 'subscription/subscribe',
    Current: 'subscription/current',
    History: 'subscription/history',
    Cancel: 'subscription/:id/cancel',
    PreviewChange: 'subscription/preview-change',
    Change: 'subscription/change',
  },
  E2E: {
    GetStatus: 'e2e/status',
    Toggle: 'e2e/toggle',
    SaveKey: 'e2e/keys',
    GetMyKey: 'e2e/keys',
    GetUserKey: 'e2e/keys/:user_id',
    DeleteKey: 'e2e/keys',
  },
  Impersonation: {
    GetAvailableUsers: 'impersonation/available-users',
    Start: 'impersonation/start',
    Stop: 'impersonation/stop',
    Status: 'impersonation/status',
    GetMyTeams: 'impersonation/my-teams',
  },
  Recordings: {
    Upload: 'recordings/upload',
    List: 'recordings',
    Get: 'recordings/:id',
    Delete: 'recordings/:id',
    Share: 'recordings/:id/share',
    Analyze: 'recordings/:id/analyze',
    MakePublic: 'recordings/:id/make-public',
    RevokePublic: 'recordings/:id/revoke-public',
    Public: 'recordings/public/:token',
  },
} as const

// Construct the URL object
export const URL_KEYS: {
  [K in keyof typeof URL]: { [P in keyof (typeof URL)[K]]: string }
} = Object.fromEntries(
  Object.entries(URL).map(([key, subKeys]) => [
    key,
    Object.fromEntries(Object.entries(subKeys).map(([subKey, path]) => [subKey, `${BASE_URL}${path}`])),
  ]),
) as {
  [K in keyof typeof URL]: { [P in keyof (typeof URL)[K]]: string }
}
