export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_OTP: '/verify-otp',
  SET_NEW_PASSWORD: '/set-new-password',
  PROFILE: '/profile',
  MANAGE_SINGLE_USERS: '/manage-users/:id',
  MANAGE_USERS: '/manage-users',
  EDIT_USERS: '/manage-users/edit',
  MANAGE_TEAM: '/manage-team',
  MANAGE_CHANNELS: '/manage-channels',
  EDIT_CHANNELS: '/manage-channels/edit',
  MANAGE_TEAM_MEMBERS: '/manage-team/:teamId',
  SETTING: '/setting',
  MANAGE_FAQS: '/manage-faqs',
  ADD_FAQ: '/manage-faqs/add',
  EDIT_FAQ: '/manage-faqs/edit/:id',
  MANAGE_PAGES: '/manage-pages',
  ADD_PAGE: '/manage-pages/add',
  EDIT_PAGE: '/manage-pages/edit/:id',
  PLANS: '/plans',
  ADD_PLAN: '/plans/add',
  EDIT_PLAN: '/plans/edit/:id',
} as const
